version: '3.5'

services:
   accounts:
     image: com.test/accounts
     ports:
       - "8081:8080"
     networks:
       - services
       - apps
   customers:
     image: com.test/customers
     ports:
       - "8082:8080"
     networks:
       - services
       - apps
   invoices:
     image: com.test/invoices
     ports:
       - "8083:8080"
     networks:
       - services
       - apps
networks:
  services:
    external:
      name: shared
  apps: {}