version: '3.5'

services:
   mysql:
     image: mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: test
       MYSQL_USER: user
       MYSQL_PASSWORD: password
     ports:
      - '3306:3306'
     expose:
      - '3306'
     networks:
      - shared
   redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - shared
   rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shared
networks:
  shared:
    name: shared